module.exports = {
    rules: {
        "extends": "eslint:recommended",
        "parserOptions": {
            "ecmaVersion": 2017,
            "sourceType": "module",
            "impliedStrict": true
        },
        "rules": {
            "array-bracket-spacing": ["error", "never"],
            "array-callback-return": "error",
            "arrow-body-style": ["warn", "as-needed", {"requireReturnForObjectLiteral": true}],
            "arrow-parens": ["warn", "as-needed"],
            "arrow-spacing": "error",
            "block-scoped-var": "error",
            "block-spacing": "error",
            "brace-style": ["error", "1tbs", {"allowSingleLine": false}],
            "camelcase": ["error", {"properties": "always"}],
            "class-methods-use-this": "warn",
            "comma-dangle": ["error", "always-multiline"],
            "comma-spacing": ["error", {"before": false, "after": true}],
            "comma-style": ["error", "last"],
            "complexity": ["warn", 8],
            "computed-property-spacing": ["error", "never"],
            "consistent-return": "error",
            "consistent-this": ["error", "self"],
            "curly": ["error", "all"],
            "default-case": "error",
            "default-case": "error",
            "dot-location": ["error", "object"],
            "eol-last": ["error", "always"],
            "eqeqeq": ["error", "always", {"null": "ignore"}],
            "func-call-spacing": ["error", "never"],
            "func-name-matching": "error",
            "func-names": ["error", "as-needed"],
            "func-style": ["error", "expression", {"allowArrowFunctions": true}],
            "generator-star-spacing": ["error", {"before": false, "after": true}],
            "global-require": "error",
            "guard-for-in": "error",
            "handle-callback-err": "warn",
            "indent": ["error", 4],
            "key-spacing": "error",
            "keyword-spacing": "error",
            "linebreak-style": ["error", "unix"],
            "lines-around-comment": ["error", {"beforeBlockComment": true, "afterBlockComment": false, "beforeLineComment": true, "afterLineComment": false, "allowBlockStart": true, "allowBlockEnd": false, "allowObjectStart": false, "allowObjectEnd": false, "allowArrayStart": false, "allowArrayEnd": false}],
            "max-depth": ["error", {"max": 5}],
            "max-len": ["error", {"code": 80, "comments": 120, "ignoreUrls": true, "ignoreTemplateLiterals": true, "ignoreRegExpLiterals": true}],
            "max-nested-callbacks": ["error", 3],
            "max-params": ["error", 4],
            "max-statements": ["error", 16],
            "max-statements-per-line": ["error", 1],
            "new-cap": ["error", {"newIsCap": false, "capIsNew": true, "properties": true}],
            "new-parens": "error",
            "newline-before-return": "error",
            "no-alert": "off",
            "no-array-constructor": "error",
            "no-caller": "error",
            "no-catch-shadow": "error",
            "no-compare-neg-zero": "error",
            "no-confusing-arrow": ["error", {"allowParens": true}],
            "no-console": "off",
            "no-duplicate-imports": ["error", {"includeExports": true}],
            "no-eval": "error",
            "no-extend-native": "error",
            "no-extra-bind": "error",
            "no-fallthrough": "error",
            "no-floating-decimal": "error",
            "no-global-assign": "error",
            "no-implicit-globals": "error",
            "no-implied-eval": "error",
            "no-invalid-this": "error",
            "no-iterator": "error",
            "no-labels": "error",
            "no-lone-blocks": "error",
            "no-lonely-if": "warn",
            "no-loop-func": "error",
            "no-magic-numbers": "error",
            "no-mixed-operators": "error",
            "no-multi-assign": "error",
            "no-multi-spaces": "error",
            "no-multi-str": "error",
            "no-multiple-empty-lines": "error",
            "no-negated-condition": "warn",
            "no-new": "error",
            "no-new-func": "error",
            "no-new-object": "error",
            "no-new-wrappers": "error",
            "no-plusplus": "error",
            "no-return-await": "error",
            "no-self-compare": "error",
            "no-sequences": "error",
            "no-shadow-restricted-names": "error",
            "no-tabs": "error",
            "no-template-curly-in-string": "error",
            "no-throw-literal": "error",
            "no-trailing-spaces": "error",
            "no-undef-init": "error",
            "no-unmodified-loop-condition": "error",
            "no-unneeded-ternary": "error",
            "no-unused-expressions": "error",
            "no-use-before-define": "error",
            "no-useless-call": "error",
            "no-useless-computed-key": "error",
            "no-useless-concat": "error",
            "no-useless-constructor": "error",
            "no-useless-escape": "error",
            "no-useless-rename": "error",
            "no-useless-return": "error",
            "no-var": "error",
            "no-whitespace-before-property": "error",
            "no-with": "error",
            "nonblock-statement-body-position": "error",
            "object-curly-newline": ["error", {"multiline": true}],
            "object-curly-spacing": ["error", "always"],
            "object-property-newline": ["error", {"allowMultiplePropertiesPerLine": true}],
            "object-shorthand": "warn",
            "one-var": ["error", "never"],
            "operator-assignment": ["warn", "always"],
            "operator-linebreak": ["warn", "after"],
            "prefer-arrow-callback": ["warn", {"allowNamedFunctions": true}],
            "prefer-const": "error",
            "prefer-destructuring": "warn",
            "prefer-numeric-literals": "error",
            "prefer-promise-reject-errors": "error",
            "prefer-rest-params": "error",
            "prefer-spread": "warn",
            "prefer-template": "warn",
            "quote-props": ["error", "consistent-as-needed", {"keywords": true, "numbers": true}],
            "quotes": ["error", "double", {"allowTemplateLiterals": true}],
            "radix": "error",
            "require-await": "warn",
            "require-jsdoc": ["error", {"require": {"FunctionDeclaration": true, "MethodDefinition": true, "ClassDeclaration": true}}],
            "rest-spread-spacing": ["error", "never"],
            "semi": ["error", "always"],
            "semi-spacing": "error",
            "space-before-blocks": ["error", "always"],
            "space-before-function-paren": ["error", {"anonymous": "always", "named": "never", "asyncArrow": "always"}],
            "space-in-parens": ["error", "never"],
            "space-infix-ops": "error",
            "space-unary-ops": ["error", {"words": true, "nonwords": false}],
            "spaced-comment": ["error", "always"],
            "strict": "error",
            "symbol-description": "error",
            "template-curly-spacing": ["warn", "never"],
            "template-tag-spacing": ["error", "never"],
            "unicode-bom": ["error", "never"],
            "valid-jsdoc": ["error", {"prefer": {"return": "returns"}, "requireReturn": false}],
            "wrap-iife": "error",
            "yield-star-spacing": ["error", "after"],
            "yoda": "warn"
        }
    }
};
